"""rich text posts

Revision ID: 115b75387e1a
Revises: af4aae97c2fb
Create Date: 2017-11-16 16:35:29.611000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115b75387e1a'
down_revision = 'af4aae97c2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
